### ISSUE TITLE
How to capture a Double click ?

### ISSUE THREAD

**Issue by gigmelepcha** [Borecjeborec1/LepikJS#1]
This works fine with electron JS, so I just wanted to ask that is there a specific method to capture a mouse double clicks?

**Comment by gigmelepcha** [comment]
Thank you for the reply, I will close the issue

**Comment by Borecjeborec1** [comment]
Hey @gigmelepcha, mouseDoubleClick just came out with version *v1.2.8*. You can try it out!  
The syntax is:
```Javascript
lepik.on("mouseDoubleClick", data => {
  console.log(data)
})
```
My apologies, for late implementation. Hope it helps.

**Comment by gigmelepcha** [comment]
Thank you, Appreciate the effort @Borecjeborec1
