### ISSUE TITLE
How to give space, enter, backspace as  key on  lepik.keyTap(key)

### ISSUE THREAD

**Issue by gigmelepcha** [Borecjeborec1/LepikJS#2]
I am in love with this package, it is having all I need for my work (Appreciate the Team),
I am having difficult time in doing certain things on keyTap, Like to press enter,space, etc, So how to give inputs value for keys haiving more than one char, like enter, space, caps locks

**Comment by gigmelepcha** [comment]
Any Updates on this issue?

**Comment by Borecjeborec1** [comment]
My bad, I thought it is already implemented, but it wasn't. 
It's done now. From **v1.2.15** and higher you can use them.

**Available inputs are:** 
`enter`, `backspace`, `capslock`, `tab`, `space`, `left`, `up`, `right`, `down`, `insert`, `delete`, `0`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`, `r`, `s`, `t`, `u`, `v`, `w`, `x`, `y`, `z`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `f10`

All are tested and works fine.
