### ISSUE TITLE
Uncaught Error: spawn ENOENT 

### ISSUE THREAD

**Issue by gigmelepcha** [Borecjeborec1/LepikJS#5]
it works fine in development, But I package and installed the software, I am getting an error related to Uncaught Error: Spawn, 
node module internally calling lepikjs winpy.exe
`Uncaught Error: spawn C:\Users\91825\AppData\Local\Programs\lokibots\resources\app.asar\node_modules\lepikjs\node_modules\lepikevents/build/winpy.exe ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:463)
    at __node_internal_errnoException (node:internal/errors:593)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282)
    at onErrorNT (node:internal/child_process:480)
    at processTicksAndRejections (node:internal/process/task_queues:83)`

**Comment by Borecjeborec1** [comment]
Uncaught Error: spawn ENOENT. *This error is almost always caused because the command does not exist, because the working directory does not exist, or from a windows-only bug.*

It looks like node cannot find the path specified. I do not think this is problem with LepikJS but with the packaging.
Have you included the LepikJS package? Not only as dev dependecy.

I will take a closer look on this problem and keep you updated.

**Comment by gigmelepcha** [comment]
Hey, Thanks for the update, 
I have deleted the Node module more than 5 times to ensure dependies, It is not in dev Dependency, I got one comment that looks like similar problem but could not follow the solution,
` https://stackoverflow.com/questions/70901907/electron-builder-not-including-entire-dependency-in-built-version `

**Comment by Borecjeborec1** [comment]
Hey there again, I am sorry for not updating this issue. Do you have any news on this? 

I made an electron app for simulating the user input events just like LepikJS does. And it compiled just fine using electron builder. I will share it, so you can check the project settings. 
Here is the link to the Cassandra project: https://github.com/Borecjeborec1/Cassandra

Maybe it us some line in package.json file. You can try changing some. If you are developing for win nsis target, try setting the extends to false and
