### ISSUE TITLE
Real-Time performance issue

### ISSUE THREAD

**Issue by Antix-Development** [Borecjeborec1/LepikJS#8]
My is an Electron based app. It is run on two computers and one is the server and the other the client. When the two computers are connected, all mouse movements from the server are sent via web socket to the client.

This works fine and I can update an HTML label with the coordinates in real-time.

However, when calling `lepik.mouseMove(x, y, true, 0)` in real-time, the performance is very slow and basically my app is unusable and the client becomes increasingly unresponsive.

I am guessing that this is a performance issue related to lepikJS.

That's fine and I can try to find another solution to my problem, but it might be good to add to the readme  that lepikJS is not a good fit for real-time applications.. that is if it's an issue with lepikJS and not my own spaghetti code :)

**Comment by Antix-Development** [comment]
Hey thanks for the reply. It's all good as I have found another module called NutJS which is able to fake input events in realtime.

My complete solution is to use LepikJs to intercept input events on my server, and then on the clients use NutJS to fake the input events.

It works really well and I'm more than happy with the results. I can now operate many computers using one, in part thanks to LepikJS! At some stage I'll tidy up my code and make the repo public.

**Comment by Antix-Development** [comment]
Whoops, forgot to close :D

**Comment by Borecjeborec1** [comment]
Hey [Antix-Development](https://github.com/Antix-Development),

just wanted to let you know, that with version 2.0.0+ the speed/user performace is no longer an issue.

I have made changes in the code so the communication is nearly instant _(~0.082ms)_!

Thanks, for the idea! I wanted to change the logic before but now I finally get to it!

**Comment by Antix-Development** [comment]
Awesome!

I eventually rewrote the application (https://github.com/Antix-Development/D2RApp) in C# because the key input module I was using was not working correctly.
