### ISSUE TITLE
Can "mouseClick" event be separated into "mouseDown" and "mouseUp"?

### ISSUE THREAD

**Issue by LiuZhenyan-Wuzhong** [Borecjeborec1/LepikJS#9]
Can "mouseClick" event be separated into "mouseDown" and "mouseUp"? That will be much powerful when coder wants to listen if user is dragging the mouse. Just an advice, feel free.

**Comment by Borecjeborec1** [comment]
Nice idea, thanks!

Both are now implemented in LepikJS v1.6.0+ and LepikEvents v1.7.0+.

In LepikJS the syntax should be: 
```javascript
lepik.on("mouseUp",(data)=>{
  console.log(data) // { x: 753, y: 241}
})
lepik.on("mouseDown",(data)=>{
  console.log(data) // { x: 753, y: 241}
})
```

Thanks for that idea again, if you have any other feature in mind, let me know and I will try to implement ASAP.

**Comment by Borecjeborec1** [comment]
It looks like mouseDown does not get called when doubleclick is performed. Instead the mouseUp gets called 2 times. 

Will be fixed in newer versions

**Comment by Borecjeborec1** [comment]
Should be fixed in _v1.6.1+_.
